import Quill from "quill";
const Parchment = Quill.import("parchment");

const config = {
  scope: Parchment.Scope.INLINE,
  whitelist: [
    "宋体",
    "微软雅黑",
    "Comic Sans MS",
    "Times New Roman",
    "等线",
    "等线 Light",
    "仿宋",
    "黑体",
    "楷体",
    "微软雅黑 Light",
    "新宋体",
    "Arial",
    "Calibri",
    "Courier New",
    "Helvetica",
    "Microsoft JhengHei",
    "Microsoft JhengHei Light",
    "Microsoft JhengHei UI",
    "Microsoft JhengHei UI Light",
    "Microsoft YaHei UI",
    "Microsoft YaHei UI Light",
    "Verdana",
    "Arial Black",
    "Bahnschrift",
    "Bahnschrift Condensed",
    "Bahnschrift Light",
    "Bahnschrift Light Condensed",
    "Bahnschrift Light SemiCondensed",
    "Bahnschrift SemiBold",
    "Bahnschrift SemiBold Condensed",
    "Bahnschrift SemiCondensed",
    "Bahnschrift SemiLight",
    "Bahnschrift SemiLight Condensed",
    "Calibri Light",
    "Cambria",
    "Cambria Math",
    "Candara",
    "Candara Light",
    "Consolas",
    "Constantia",
    "Corbel",
    "Corbel Light",
    "Courier",
    "Ebrima",
    "Franklin Gothic",
    "Franklin Gothic Medium",
    "Gabriola",
    "Gadugi",
    "Georgia",
    "HoloLens MDL2 Assets",
    "Impact",
    "Ink Free",
    "Javanese Text",
    "Leelawadee UI",
    "Lucida Console",
    "Lucida Sans Unicode",
    "Malgun Gothic",
    "Marlett",
    "Microsoft Himalaya",
    "Microsoft New Tai Lue",
    "Microsoft PhagsPa",
    "Microsoft Sans Serif",
    "Microsoft Tai Le",
    "Microsoft Yi Baiti",
    "MingLiU_HKSCS-ExtB",
    "MingLiU-ExtB",
    "Mongolian Baiti",
    "MS Gothic",
    "MS PGothic",
    "MS UI Gothic",
    "MV Boli",
    "Myanmar Text",
    "Nirmala UI",
    "Palatino Linotype",
    "PMingLiU-ExtB",
    "Segoe MDL2 Assets",
    "Segoe Print",
    "Segoe Script",
    "Segoe UI",
    "Segoe UI Black",
    "Segoe UI Emoji",
    "Segoe UI Historic",
    "Segoe UI Light",
    "Segoe UI Semibold",
    "Segoe UI Symbol",
    "SimSun-ExtB",
    "Sitka Banner",
    "Sitka ImageDisplay",
    "Sitka Heading",
    "Sitka Small",
    "Sitka Subheading",
    "Sitka Text",
    "Sylfaen",
    "Symbol",
    "Tahoma",
    "Times",
    "Trebuchet MS",
    "Yu Gothic",
    "Yu Gothic Light",
    "Yu Gothic Medium",
    "Yu Gothic UI",
    "Yu Gothic UI Light",
    "Yu Gothic UI Semibold",
  ],
};

const FontClass = new Parchment.ClassAttributor("font", "ql-font", config);

class FontStyleAttributor extends Parchment.StyleAttributor {
  value(node: HTMLElement) {
    return super.value(node).replace(/["']/g, "");
  }
}

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
const FontStyle = new FontStyleAttributor("font", "font-family", config);

export { FontStyle, FontClass };
